[package]
name = "PKG_NAME"
version = "0.1.0"
authors = ["PKG_NAME authors"]
edition = "2024"

[dependencies]
mproto = { version = "0.2", default-features = false }

[features]
default = ["std"]
std = ["mproto/std"]
alloc = ["mproto/alloc"]
